version: '3.3'

services:

  db:
    image: freds00n/basicproject_db:latest
    container_name: mysql-basicproject
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - "3306"
        
    restart: always
    volumes:
      - mysql_data_container_project:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    container_name: my-php-myadmin-basicproject
    ports:
      - "8082:80"
    restart: always
  
#  book-info-service:
#    depends_on:
#      - db
#    image: freds00n/basicproject:latest
#    container_name: basicproject
#    environment:
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#    ports:
#      - "8051:8051"

volumes:
  mysql_data_container_project:
