version: '3.3'

services:

  db:
    image: freds00n/basicproject_db:latest
    container_name: mysql-basicproject
    environment:
      - MYSQL_DATABASE=${database}
      - MYSQL_ROOT_PASSWORD=${password}
    ports:
      - "3306:3306"
    restart: always
    expose:
      - "3306"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    container_name: my-php-myadmin-basicproject
    ports:
      - "8082:80"
    restart: always
  
  api-service:
    depends_on:
      - db
    links:
      - db
    image: freds00n/basicproject:latest
    container_name: basicproject
    ports:
      - "8051:8051"
    restart: always
