name: GitHub Test suite
on: push


jobs:
  build:
    runs-on: 'ubuntu-latest'
    env:
      MYSQL_DATABASE: ${{ secrets.DATABASE }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build &amp; run tests
      run: |
        docker-compose -f docker-compose.yml up \
          --abort-on-container-exit