name: Deliver container

on: push

jobs:
  delivery:
    runs-on: ubuntu-latest
    name: Deliver container
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/basicproject:latest .
          RUN mkdir env
          RUN touch env/.env
          echo DOCKER_USER="$DOCKER_USER" >> ./env/.env
          echo DOCKER_PASSWORD="$DOCKER_PASSWORD" >> ./env/.env
          ls -a
          cat env/.env

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/basicproject:latest
